name: Build-Debug

on:
  push:
    branches:
      - "develop"
jobs:
  build:
    name: Build binary
    runs-on: windows-2022
    strategy:
      matrix:
        configuration:
          - Debug
    steps:
      - name: Wait for previous workflows
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out files
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Generate project files
        run: tools/premake5 vs2022

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}} binaries
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=Win32 build/iw3xo-dev.sln

      - name: Upload ${{matrix.configuration}} binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.configuration}} binaries
          path: |
            build/bin/${{matrix.configuration}}/iw3x.dll
            build/bin/${{matrix.configuration}}/iw3x.pdb